export const products = [
    {
        id: "product-1",
        name: "Techify Wireless Headphones",
        price: 8999,
        category: "Electronics",
        description: "Noise-cancelling wireless headphones with 40-hour battery life.",
        imageUrl: "https://images.example.com/products/headphones.jpg",
        warrantyMonths: 12,
        freeShippingOn: true,
        returnAvailable: true,
        brandId: "brand-1",
    },
    {
        id: "product-2",
        name: "Techify Smartwatch Pro",
        price: 14999,
        category: "Wearables",
        description: "Advanced smartwatch with health tracking and GPS.",
        imageUrl: "https://images.example.com/products/smartwatch.jpg",
        warrantyMonths: 18,
        freeShippingOn: true,
        returnAvailable: true,
        brandId: "brand-1",
    },
    {
        id: "product-3",
        name: "UrbanWear Oversized Hoodie",
        price: 2499,
        category: "Fashion",
        description: "Comfortable oversized hoodie made from premium cotton.",
        imageUrl: "https://images.example.com/products/hoodie.jpg",
        warrantyMonths: null,
        freeShippingOn: false,
        returnAvailable: true,
        brandId: "brand-2",
    },
];
